spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_jpa?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
